<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\BusinessPartner;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker; // Import Faker

class BusinessPartnerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // It's good practice to truncate the table before seeding to start fresh
        // but be careful with this in a production environment.
        BusinessPartner::truncate();

        $faker = Faker::create('id_ID'); // Use Indonesian locale for more realistic data

        // Create 20 sample business partners
        foreach (range(1, 20) as $index) {
            BusinessPartner::create([
                // 'code' will be auto-generated by the model, so we don't need to set it here.
                'name' => $faker->company,
                'phone' => $faker->phoneNumber,
                'photo_url' => null, // Or use $faker->imageUrl() if you want placeholder images
                'partner_type' => $faker->randomElement(['customer', 'supplier']),
                'description' => $faker->sentence,
                'is_active' => $faker->boolean(90), // 90% chance of being active
                'address' => $faker->address,
            ]);
        }
    }
}
