<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Item;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker; // Import Faker

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // It's good practice to truncate the table before seeding to start fresh
        // but be careful with this in a production environment.
        Item::truncate();

        $faker = Faker::create('id_ID');

        // Create 50 sample items
        foreach (range(1, 50) as $index) {
            Item::create([
                // 'code' will be auto-generated by the model.
                'name' => $faker->unique()->word . ' ' . $faker->word,
                'unit' => $faker->randomElement(['EA', 'SHEET']),
                'price' => $faker->numberBetween(10000, 1000000),
                'description' => $faker->sentence(10),
                'is_active' => $faker->boolean(95), // 95% chance of being active
                'photo_url' => null, // Or use $faker->imageUrl()
            ]);
        }
    }
}
